# Generated by Django 3.0.6 on 2020-10-18 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='groupId',
            field=models.CharField(default=False, max_length=100, verbose_name='GroupId'),
        ),
    ]
